title: ADPTGroup 
author: adpt
email: info@adpt.com 
description: > # this means to ignore newlines until "baseurl:"
  Change Everthing

twitter_username: adptgroup
github_username:  adptgroup

sass:
    style: compressed
